appendMatches <- function(Z, matches) {
  
  # Get Ki for each control unit from the logical matrix generated by getMatch
  K <- rowSums(matches)
  
  # Ki is defined as 0 for treated units, so we need to find N1
  tSample <- Z[which(Z[,2] == 1),]
  n1 <- length(tSample[,2])
  
  Ki <- c(rep(0, times=n1),K)
  
  Z <- cbind(Z, Ki)
  
  return(Z)
}
