# getMatch()
# 
# An optimized version of findMatches(), using apply whenever possible.

# Outline:
# For each treated unit i, find the distance between it's covariate and the
# covariate value of each control unit. Then, select the control unit(s)
# that have the smallest value as the matches. Construct matching matrix
# column-by-column in this fashion.

# The input, Z, is expected to be the kind of thing generated by dgpFun().

getMatch <- function(Z) {
  
  require(Matrix)
  
  # Split the input into treated and untreated subsets, and get the values
  # of N1 and N0.
  treatedSample <- Z[which(Z[,2] == 1),]
  controlSample <- Z[which(Z[,2] == 0),]
  
  n1 <- length(treatedSample[,1])
  n0 <- length(controlSample[,1])
  
  # Calculate all the relevant distances
  distMatrix <- apply(treatedSample, 1, function(x) abs(x[1] - controlSample[,1]))
  # distMatrix is an N0 x N1 matrix. The ij'th element is the distance between
  # the covariate value of the j'th treated unit and the i'th control unit.
  
  # We want to find the row(s) which contain the lowest value(s) for each i.
  # These rows are the matching control units.
  matches <- Matrix(apply(distMatrix, 2, function(x) x == min(x)), sparse = TRUE)
  
  
  return(matches)
  
}
                          
# UNIT TEST PASSED ON
# JUNE 14 2017
